---
- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    password: "{{ item.password }}"
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
  loop: "{{ users }}"
  
- name: Give user1 more limits
  ansible.builtin.copy:
    src: user1.conf
    dest: /etc/security/limits.d/user1.conf
    owner: root
    group: root
    mode: 0644
  when: item.name == 'user1'
  loop: "{{ users }}"

- name: Kernel hardening
  ansible.builtin.copy:
    src: kernel_hardening.conf
    dest: /etc/sysctl.d/99-kernel_hardening.conf
    owner: root
    group: root
    mode: 0644
  